### ISSUE TITLE
Short audio sounds different than it should (not sure if this is an oddio issue)

### ISSUE THREAD

**Issue by Nazariglez** [Ralith/oddio#100]
Hey! 

We have this issue on [notan](https://github.com/Nazariglez/notan/issues/206) where short audio seems to sound different depending on where you reproduce it. I am not sure at all that this is an issue on notan, Oddio, o maybe Symphonia, but I have been stuck with this for a while, and I was thinking that perhaps it is a good idea to ask here to see if this ring any bell and somebody can give me a hint or point me in the right direction. 

Thanks!

Issue: https://github.com/Nazariglez/notan/issues/206

**Comment by Ralith** [comment]
On inspection in Audacity, the glitched version of the audio looks like it's being played at twice the intended speed. I also note that the source is a monophonic .wav, but the incorrect playback was recorded in stereo. I haven't seen a bug like that in the past, but perhaps some part of your pipeline is erroneously interpreting it as stereo data and de-interleaving it into two half-duration streams?

Otherwise, I'd encourage you to try to build a minimal self-contained repro.

**Comment by Nazariglez** [comment]
You're totally right, I was treating all sources as stereo without checking if they were mono or converting them to mono. 

Thanks for the help!
