### ISSUE TITLE
SpatialScene walk_set not stopping Streams correctly

### ISSUE THREAD

**Issue by exjam** [Ralith/oddio#86]
I am using a `Handle<SpatialBuffered<Stop<Gain<Stream<f32>>>>>`.

I am streaming audio from a file, and when I reach the end of the file I drop the handle. This means I am relying on the handle_dropped check to signal to the Stream that it is closed, and to allow remaining buffered audio in Stream to drain.

However I notice that the signal is never actually stopped and removed from the set because of the check including distance - obviously it is very very unlikely that distance will ever reach 0 for most spatial sounds. So none of my spatial sounds are ever stopped and end up leaking memory - and once there are enough sounds it affects playback peformance too.

https://github.com/Ralith/oddio/blob/60d4c8735d16a990a7bb5d0eb73d46dd737dda36/src/spatial.rs#L250-L254

**Comment by Ralith** [comment]
Good catch! That condition is designed on the assumption that `remaining()` will gradually become more negative, as it does in the case of `Frames`. However, `Stream::advance` is designed to prevent the cursor from growing in magnitude without bound so that long-running streams don't run into precision issues. I think this should be fixed by special-casing closed streams in `advance` and allowing the cursor to grow in that case. I'll have a go at that tonight.
